repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: minio
    namespace: storage
    chart: bitnami/minio
    version: 15.0.4
    values:
      - ./values/minio.yaml
  - name: redis
    namespace: storage
    chart: bitnami/redis
    version: 20.8.0
    values:
      - ./values/redis.yaml
